# Config
baseurl:
url: 'http://example.com'
markdown: kramdown

# Site
title: Jekyll Maps

# Map
map-tileset: 'http://{s}.tile.stamen.com/toner-lite/{z}/{x}/{y}.png'
map-credits: '<a target="_blank" href="https://github.com/svmatthews/jekyll-maps">Jekyll Maps</a> | Tiles: Stamen & OSM'